[tool.poetry]
name = "uvicorn-gunicorn-poetry"
version = "1.1.0"
description = "Gunicorn with Uvicorn workers for running web applications. Uses Poetry for managing dependencies and setting up a virtual environment."
authors = ["Max Pfeiffer <max@maxpfeiffer.ch>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.9.*"
python-dotenv = "0.19.1"

[tool.poetry.dev-dependencies]
pytest = "7.1.3"
pytest-cov = "3.0.0"
coverage = "6.4.4"
docker = "6.0.0"
requests = "2.28.1"
black = "22.8.0"
pre-commit = "2.20.0"
semver = "2.13.0"


# https://docs.pytest.org/en/latest/reference/customize.html
[tool.pytest.ini_options]
addopts = "--ignore=tests/functionality/test_worker_reload.py"
testpaths = [
    "tests",
]

# https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-via-a-file
[tool.black]
line-length = 80
target-version = ['py39']

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
